### ISSUE TITLE
How to put a pgp key if there is no gnupg and the repository itself does not work? (kalifs-mini)

### ISSUE THREAD

**Issue by NightFlexer** [AlexeyZavar/nethunter-installation#1]

**Comment by NightFlexer** [comment]
Your instruction doesn't work because there is no gnupg package

**Comment by AlexeyZavar** [comment]
this instruction is 2 years old, i haven't touched kali for a long time. but if the guys haven't been able to fix the bug for over 2 years, then why use nethunter at all 😆 
just use desktop kali.

btw, if you have solved this problem, post the solution here
